apiVersion: v1
kind: PersistentVolume
metadata:
  name: cv-master-pv
  labels:
    app: curvine
    component: master
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /Users/ruoyuhuang/curvine/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cv-master-pvc
  namespace: curvine
  labels:
    app: curvine
    component: master
spec:
  volumeName: cv-master-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cv-master-log-pv
  labels:
    app: curvine
    component: master
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /Users/ruoyuhuang/curvine/logs
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cv-master-log-pvc
  namespace: curvine
  labels:
    app: curvine
    component: master
spec:
  volumeName: cv-master-log-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cv-master
  namespace: curvine
  labels:
    app: curvine
    component: master
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: curvine
    component: master
  ports:
    - name: rpc
      port: 8995
      targetPort: 8995
      protocol: TCP
    - name: journal
      port: 8996
      targetPort: 8996
      protocol: TCP
    - name: web
      port: 9000
      targetPort: 9000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cv-master-web
  namespace: curvine
  labels:
    app: curvine
    component: master
spec:
  type: NodePort
  selector:
    app: curvine
    component: master
  ports:
    - name: web
      port: 9000
      targetPort: 9000
      nodePort: 30900
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cv-master
  namespace: curvine
  labels:
    app: curvine
    component: master
spec:
  serviceName: cv-master
  replicas: 1
  selector:
    matchLabels:
      app: curvine
      component: master
  template:
    metadata:
      labels:
        app: curvine
        component: master
    spec:
      containers:
        - name: cv-master
          image: localhost:5001/curvine:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - "/entrypoint.sh master start"
          ports:
            - name: rpc
              containerPort: 8995
              protocol: TCP
            - name: journal
              containerPort: 8996
              protocol: TCP
            - name: web
              containerPort: 9000
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CURVINE_MASTER_HOSTNAME
              value: "cv-master-0.cv-master.curvine.svc.cluster.local"
            - name: CURVINE_HOME
              value: /app/curvine
            - name: CURVINE_CONF_FILE
              value: "/app/curvine/conf/curvine-cluster.toml"
            - name: RUST_LOG
              value: "debug"
            - name: RUST_LOG
              value: "curvine=debug,orpc=info,tokio=warn"
            - name: RUST_BACKTRACE
              value: "1"
          volumeMounts:
            - name: config
              mountPath: /app/curvine/conf/curvine-cluster.toml
              subPath: curvine-cluster.toml
              readOnly: true
            - name: data
              mountPath: /app/curvine/data
            - name: log
              mountPath: /app/curvine/logs
          livenessProbe:
            tcpSocket:
              port: 8995
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 8995
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "4Gi"
      volumes:
        - name: config
          configMap:
            name: curvine-config
            items:
              - key: curvine-cluster.toml
                path: curvine-cluster.toml
        - name: data
          persistentVolumeClaim:
            claimName: cv-master-pvc
        - name: log
          persistentVolumeClaim:
            claimName: cv-master-log-pvc
          

