apiVersion: v1
kind: Service
metadata:
  name: cv-worker
  namespace: curvine
  labels:
    app: curvine
    component: worker
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: curvine
    component: worker
  ports:
    - name: rpc
      port: 8997
      targetPort: 8997
      protocol: TCP
    - name: web
      port: 9001
      targetPort: 9001
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-worker
  namespace: curvine
  labels:
    app: curvine
    component: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: curvine
      component: worker
  template:
    metadata:
      labels:
        app: curvine
        component: worker
    spec:
      affinity:
        # Prefer spreading workers across different nodes
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: component
                      operator: In
                      values:
                        - worker
                topologyKey: kubernetes.io/hostname
      containers:
        - name: cv-worker
          image: localhost:5001/curvine:latest
          imagePullPolicy: IfNotPresent 
          command:
            - /bin/bash
            - -c
            - "/entrypoint.sh worker start"
          ports:
            - name: rpc
              containerPort: 8997
              protocol: TCP
            - name: web
              containerPort: 9001
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CURVINE_HOME
              value: /app/curvine
            - name: CURVINE_WORKER_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CURVINE_MASTER_HOSTNAME
              value: "cv-master-0.cv-master.curvine.svc.cluster.local"
            - name: CURVINE_CONF_FILE
              value: "/app/curvine/conf/curvine-cluster.toml"
            - name: RUST_LOG
              value: "info"
            - name: RUST_BACKTRACE
              value: "1"
          volumeMounts:
            - name: config
              mountPath: /app/curvine/conf/curvine-cluster.toml
              subPath: curvine-cluster.toml
              readOnly: true
            - name: data
              mountPath: /app/curvine/data
            - name: log
              mountPath: /app/curvine/logs
          livenessProbe:
            tcpSocket:
              port: 8997
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 8997
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "2000m"
              memory: "8Gi"
      volumes:
        - name: config
          configMap:
            name: curvine-config
            items:
              - key: curvine-cluster.toml
                path: curvine-cluster.toml
        - name: data
          emptyDir: {}
        - name: log
          emptyDir: {}
