apiVersion: v1
kind: ConfigMap
metadata:
  name: curvine-config
  namespace: curvine-system
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: curvine-csi-controller
data:
  curvine-cluster.toml: |
    # Customer service configuration.
    [client]
    master_addrs = [
        { hostname = "cv-master-0.cv-master-svc.curvine.svc.cluster.local", port = 8995 },
        { hostname = "cv-master-1.cv-master-svc.curvine.svc.cluster.local", port = 8995 },
        { hostname = "cv-master-2.cv-master-svc.curvine.svc.cluster.local", port = 8995 },
    ]

    # fuse configuration
    [fuse]


    # The log configuration of the customer service side, and the customer service side of rust, java, and fuse use this log file.
    [log]
    level = "info"
    log_dir = "stdout"
    file_name = "curvine.log"
  curvine-env.sh: |
    export CURVINE_HOME="$(cd "$(dirname "$0")"/..; pwd)"
    export CURVINE_CONF_FILE=$CURVINE_HOME/conf/curvine-cluster.toml
